# Generated by Django 5.2.11 on 2026-04-04 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("utilisateur", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "identifiant",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("retail", "Retail"),
                            ("industrie", "Industrie"),
                            ("distribution", "Distribution"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("candidatures", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Secteur",
                "ordering": ["-nom"],
            },
        ),
        migrations.AlterModelOptions(
            name="users",
            options={
                "ordering": ["-last_login", "-is_active", "-date_joined"],
                "verbose_name": "User Delior",
            },
        ),
        migrations.AddField(
            model_name="users",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "identifiant",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.CharField(max_length=100)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("Infos", "Infos"),
                            ("Succes", "Succes"),
                            ("Error", "Error"),
                            ("Warning", "Warning"),
                        ],
                        max_length=8,
                    ),
                ),
                ("lue", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message Agent",
                "ordering": ["-date_creation", "-tag"],
                "indexes": [
                    models.Index(
                        fields=["date_creation"], name="utilisateur_date_cr_6b38dd_idx"
                    ),
                    models.Index(fields=["lue"], name="utilisateur_lue_ed75eb_idx"),
                    models.Index(fields=["tag"], name="utilisateur_tag_ae7e1b_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="users",
            name="notification",
            field=models.ManyToManyField(
                blank=True, related_name="users_notif", to="utilisateur.notification"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["last_name"], name="utilisateur_last_na_b6e7b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["first_name"], name="utilisateur_first_n_279c02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(fields=["email"], name="utilisateur_email_82e959_idx"),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(fields=["post"], name="utilisateur_post_2156c5_idx"),
        ),
        migrations.AddIndex(
            model_name="secteur",
            index=models.Index(fields=["nom"], name="utilisateur_nom_b4aae2_idx"),
        ),
    ]
