# Generated by Django 5.2.11 on 2026-04-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateur", "0002_secteur_alter_users_options_users_last_seen_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Secteur",
        ),
    ]
