# Generated by Django 5.2.11 on 2026-02-07 21:39

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CandidatCV",
            fields=[
                (
                    "candidat_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom_complet", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=50)),
                ("ville", models.CharField(blank=True, max_length=150)),
                ("titre_professionnel", models.CharField(blank=True, max_length=255)),
                ("resume_profil", models.TextField(blank=True)),
                ("donnees_structurees", models.JSONField(default=dict)),
                (
                    "fichier_pdf_origine",
                    models.FileField(blank=True, null=True, upload_to="cv_pdfs/"),
                ),
                ("date_importation", models.DateTimeField(auto_now_add=True)),
                (
                    "competences",
                    models.ManyToManyField(
                        blank=True, related_name="candidats", to="candidat.competence"
                    ),
                ),
            ],
            options={
                "verbose_name": "CV Candidat",
                "ordering": ["-date_importation"],
            },
        ),
        migrations.CreateModel(
            name="RapportCv",
            fields=[
                (
                    "rapport_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenu", models.JSONField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "candidatcv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatcvs",
                        to="candidat.candidatcv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport Cv Candidat",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(fields=["email"], name="candidat_ca_email_e9e73b_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(
                fields=["titre_professionnel"], name="candidat_ca_titre_p_9592cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(fields=["ville"], name="candidat_ca_ville_9b15d6_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["donnees_structurees"], name="candidat_ca_donnees_566fa1_gin"
            ),
        ),
    ]
