# Generated by Django 5.2.11 on 2026-04-04 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_deliore", models.EmailField(blank=True, max_length=254)),
                (
                    "password_email_deliore",
                    models.CharField(blank=True, max_length=255),
                ),
                ("email_loader_status", models.BooleanField(default=False)),
                ("email_processing_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configuration",
            },
        ),
        migrations.CreateModel(
            name="QueryMatching",
            fields=[
                (
                    "query_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("date_importation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Query Agent",
                "ordering": ["-date_importation"],
            },
        ),
        migrations.AlterModelOptions(
            name="candidatcv",
            options={
                "ordering": [
                    "-date_importation",
                    "-etat_analyse_termine",
                    "-etat_analyse",
                ],
                "verbose_name": "CV Candidat",
            },
        ),
        migrations.AlterModelOptions(
            name="competence",
            options={"ordering": ["-nom"], "verbose_name": "Competence"},
        ),
        migrations.AddField(
            model_name="candidatcv",
            name="actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="candidatcv",
            name="agent_analyse_cv",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidats_analyse_cv",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidatcv",
            name="etat_analyse",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_cours", "En cours"),
                    ("termine", "Terminé"),
                ],
                default="en_attente",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="candidatcv",
            name="etat_analyse_termine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidatcv",
            name="preview_image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="cv_previews/"
            ),
        ),
        migrations.AddField(
            model_name="rapportcv",
            name="actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="fichier_pdf_origine",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="cv_pdfs/"
            ),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="nom_complet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="competence",
            name="nom",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(
                fields=["etat_analyse_termine"], name="candidat_ca_etat_an_b45e03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(
                fields=["etat_analyse"], name="candidat_ca_etat_an_298a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competence",
            index=models.Index(fields=["nom"], name="candidat_co_nom_f072f6_idx"),
        ),
        migrations.AddIndex(
            model_name="rapportcv",
            index=models.Index(fields=["actif"], name="candidat_ra_actif_ecc0bb_idx"),
        ),
        migrations.AddField(
            model_name="querymatching",
            name="agent_deliore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="querymatching",
            index=models.Index(
                fields=["date_importation"], name="candidat_qu_date_im_9912d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querymatching",
            index=models.Index(
                fields=["agent_deliore"], name="candidat_qu_agent_d_370a2a_idx"
            ),
        ),
    ]
