# Generated by Django 5.2.11 on 2026-04-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidat",
            "0002_configuration_querymatching_alter_candidatcv_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatcv",
            name="domaine",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="candidatcv",
            name="secteur",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
