# Generated by Django 5.2.11 on 2026-04-04 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0003_candidatcv_domaine_candidatcv_secteur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidatcv",
            options={
                "ordering": [
                    "-date_importation",
                    "-etat_analyse_termine",
                    "-etat_analyse",
                    "-domaine",
                    "-secteur",
                ],
                "verbose_name": "CV Candidat",
            },
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(
                fields=["domaine"], name="candidat_ca_domaine_3c0c45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(
                fields=["secteur"], name="candidat_ca_secteur_e3af02_idx"
            ),
        ),
    ]
