# Generated by Django 5.2.11 on 2026-04-07 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0004_alter_candidatcv_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidatcv",
            options={
                "ordering": [
                    "-date_importation",
                    "-etat_analyse_termine",
                    "-etat_analyse",
                    "-domaine",
                    "-secteur",
                    "-niveau",
                ],
                "verbose_name": "CV Candidat",
            },
        ),
        migrations.AddField(
            model_name="candidatcv",
            name="niveau",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(fields=["niveau"], name="candidat_ca_niveau_c99872_idx"),
        ),
    ]
