# Generated by Django 5.2.11 on 2026-04-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0005_alter_candidatcv_options_candidatcv_niveau_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatcv",
            name="contrat_souhaite",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="candidatcv",
            name="poste_souhaite",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
