# Generated by Django 5.2.11 on 2026-04-27 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0006_candidatcv_contrat_souhaite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatcv",
            name="pays",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="candidatcv",
            index=models.Index(fields=["pays"], name="candidat_ca_pays_47030b_idx"),
        ),
    ]
