# Generated by Django 5.2.11 on 2026-04-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0007_candidatcv_pays_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatcv",
            name="poste_souhaite",
        ),
    ]
