# Generated by Django 5.2.11 on 2026-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0008_remove_candidatcv_poste_souhaite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatcv",
            name="telephone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
