# Generated by Django 5.2.11 on 2026-05-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0009_alter_candidatcv_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatcv",
            name="competences",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="candidats",
                to="candidat.competence",
            ),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="contrat_souhaite",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="domaine",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="niveau",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="pays",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="resume_profil",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="secteur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="titre_professionnel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidatcv",
            name="ville",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
