# Generated by Django 6.0.6 on 2026-06-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0010_alter_candidatcv_competences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatcv',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='candidats', to='candidat.competence'),
        ),
    ]
